## Visualisation Presentation
For this presentation I will be using a kaggle datset (https://www.kaggle.com/code/fulviocapra/sc2-iem-katowice-data-analytics/notebook)

This is analylitical data about Sc2 pro games during the Intel Extreme Master (IEM) esports tournament held in Katowice, Poland.
I will clean, display and draw insights from the data using the python packages show below.

In [22]:
# Importing the packages.
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib as plt

In [23]:
# Now i will import the csv dataset from locally
iem = pd.read_csv("IEM_games.csv")
iem.head()

,Unnamed: 0,Year,Date,Time,Player1,Player2,MapName,Length,Race1,Race2,...,APM2,AvgSPM,SPM1,SPM2,AvgSQ,SQ1,SQ2,AvgPSC,PSC1,PSC2
0,1,2016,03-05,17:17:08,Polt,Snute,RuinsOfSeras,23:26,T,Z,...,248,17.163381,14.196245,20.137111,77,69,86,3.337298,5.128205,1.546392
1,2,2016,03-05,16:52:16,Polt,Snute,Ulrena,12:23,T,Z,...,263,18.672701,14.107624,23.208086,87,86,87,8.285741,6.862745,9.708738
2,3,2016,03-05,16:32:38,Polt,Snute,CentralProtocol,13:07,T,Z,...,308,14.074966,13.373235,14.778725,92,91,93,11.009174,7.339450,14.678899
3,4,2016,03-05,16:12:22,Polt,Snute,PrionTerraces,07:19,T,Z,...,240,19.217802,14.791656,23.669906,103,110,96,9.016393,8.196721,9.836066
4,5,2016,03-05,16:02:56,Polt,Snute,OrbitalShipyard,17:03,T,Z,...,268,18.318570,16.786930,19.855524,96,99,92,7.783938,4.929577,10.638298

## Understanding the Data
Though most of the columns are have obvious meaning, Their are some player statistics that will need to be explained to those unfamilar is RTS terminology.

- **APM** - actions per minute - This refers to the amount of keyboard and mouse clicks that occur within a minute. This is used as a way of measuring a players speed and therefore skill. Not always accurate as alot of spamming* occurs.


- **SPM** - screens per minute - Refers to how many screens are processed a minute. Similar to apm it is a measure of speed and is not always 
accurate due to spamming*


- **SQ** - spending quotient - **add explanation here USING LATEX**

- **PSC** - percentage supply capped - Shows the time the player was supply capped* during the game as a percentage of total game length.

## Cleaning the data

In [24]:
# The data itself is already in good shape, index column can be removed
iem.drop(columns = "Unnamed: 0", inplace = True)

In [ ]:
# I can also optionally split data into years to make certain process easier